-- ========================================
-- MIGRACAO: Tabelas de analytics e historico
-- Data: 19/03/2026
-- Proposito: Criar estruturas aditivas para eventos, agregados diarios e arquivamento
-- ========================================

-- 1. message_events - trilha granular de eventos de entrega
CREATE TABLE IF NOT EXISTS public.message_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID REFERENCES public.patients_queue(id) ON DELETE CASCADE,
  instance_id UUID REFERENCES public.whatsapp_instances(id) ON DELETE SET NULL,
  to_phone TEXT,
  event_type TEXT NOT NULL CHECK (
    event_type IN (
      'send_accepted',
      'delivered',
      'read',
      'replied',
      'failed',
      'not_received_timeout',
      'followup_sent',
      'retry_phone2_sent',
      'status_queued',
      'status_sending',
      'status_delivered',
      'status_failed',
      'status_cancelled'
    )
  ),
  event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  raw_payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.message_events IS 'Eventos granulares de mensageria para analytics e trilha de status';
COMMENT ON COLUMN public.message_events.raw_payload IS 'Payload resumido do evento para auditoria e depuracao';

CREATE INDEX IF NOT EXISTS idx_message_events_message_id
  ON public.message_events(message_id);

CREATE INDEX IF NOT EXISTS idx_message_events_event_type
  ON public.message_events(event_type, event_at DESC);

CREATE INDEX IF NOT EXISTS idx_message_events_instance_id
  ON public.message_events(instance_id);

CREATE INDEX IF NOT EXISTS idx_message_events_daily
  ON public.message_events(((event_at AT TIME ZONE 'America/Cuiaba')::date), event_type);

CREATE INDEX IF NOT EXISTS idx_message_events_message_id_event_type
  ON public.message_events(message_id, event_type);

ALTER TABLE public.message_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'message_events'
      AND policyname = 'Allow authenticated operations on message_events'
  ) THEN
    CREATE POLICY "Allow authenticated operations on message_events"
      ON public.message_events FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 2. analytics_daily - agregado diario para dashboard principal
CREATE TABLE IF NOT EXISTS public.analytics_daily (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data DATE NOT NULL UNIQUE,
  total_enviadas INTEGER NOT NULL DEFAULT 0,
  sucesso INTEGER NOT NULL DEFAULT 0,
  falha INTEGER NOT NULL DEFAULT 0,
  cancelada INTEGER NOT NULL DEFAULT 0,
  por_procedimento JSONB NOT NULL DEFAULT '{}'::jsonb,
  avg_time_to_delivery_minutes NUMERIC(10,2),
  avg_retry_count NUMERIC(10,2),
  instances_used INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.analytics_daily IS 'Agregado diario para dashboard principal e historico de performance';
COMMENT ON COLUMN public.analytics_daily.por_procedimento IS 'Objeto JSON com contadores por procedimento para o dia';

CREATE INDEX IF NOT EXISTS idx_analytics_daily_data_desc
  ON public.analytics_daily(data DESC);

ALTER TABLE public.analytics_daily ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'analytics_daily'
      AND policyname = 'Allow authenticated read analytics_daily'
  ) THEN
    CREATE POLICY "Allow authenticated read analytics_daily"
      ON public.analytics_daily FOR SELECT TO authenticated USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'analytics_daily'
      AND policyname = 'Allow authenticated write analytics_daily'
  ) THEN
    CREATE POLICY "Allow authenticated write analytics_daily"
      ON public.analytics_daily FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- 3. patients_queue_archive - espelho de backup para limpeza operacional
CREATE TABLE IF NOT EXISTS public.patients_queue_archive (
  id UUID PRIMARY KEY,
  patient_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  message_body TEXT NOT NULL,
  status TEXT NOT NULL,
  is_approved BOOLEAN NOT NULL,
  send_after TIMESTAMPTZ NOT NULL,
  queue_order INTEGER,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  data_exame TEXT,
  Data_nascimento TEXT,
  procedimentos TEXT,
  time_proce TEXT,
  horario_inicio TIME,
  horario_final TIME,
  phone_2 TEXT,
  phone_3 TEXT,
  is_landline BOOLEAN,
  locked_by TEXT,
  locked_at TIMESTAMPTZ,
  attempt_count INTEGER,
  send_accepted_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  read_at TIMESTAMPTZ,
  replied_at TIMESTAMPTZ,
  last_delivery_status TEXT,
  needs_second_call BOOLEAN,
  second_call_reason TEXT,
  retry_phone2_sent_at TIMESTAMPTZ,
  followup_sent_at TIMESTAMPTZ,
  last_contact_phone TEXT,
  dedupe_kind TEXT,
  canonical_phone TEXT,
  origin_queue_id UUID,
  dedupe_hash TEXT,
  archived_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archived_reason TEXT,
  archived_by TEXT
);

COMMENT ON TABLE public.patients_queue_archive IS 'Backup operacional de pacientes removidos da fila principal por arquivamento manual';

CREATE INDEX IF NOT EXISTS idx_patients_queue_archive_data_exame
  ON public.patients_queue_archive(data_exame);

CREATE INDEX IF NOT EXISTS idx_patients_queue_archive_archived_at
  ON public.patients_queue_archive(archived_at DESC);

CREATE INDEX IF NOT EXISTS idx_patients_queue_archive_status
  ON public.patients_queue_archive(status);

CREATE INDEX IF NOT EXISTS idx_patients_queue_archive_procedimentos
  ON public.patients_queue_archive(procedimentos);

ALTER TABLE public.patients_queue_archive ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'patients_queue_archive'
      AND policyname = 'Allow authenticated operations on patients_queue_archive'
  ) THEN
    CREATE POLICY "Allow authenticated operations on patients_queue_archive"
      ON public.patients_queue_archive FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;
